((nil . ((ispell-local-dictionary . "american")
         (sentence-end-double-space . t)
         (fill-column . 79)
         (eval . (when (and (boundp 'projectile-project-types)
                            (alist-get 'pk/emacs-package projectile-project-types))
                   (setq projectile-project-type 'pk/emacs-package)))))
 (emacs-lisp-mode . ((indent-tabs-mode . nil)
                     (flycheck-emacs-lisp-load-path . inherit)))
 (org-mode . ((eval . (progn
                        (when (fboundp 'org-make-toc)
                          (add-hook 'before-save-hook #'org-make-toc nil t))
                        (when (fboundp 'org-commentary-update)
                          (add-hook 'after-save-hook #'org-commentary-update nil t)))))))
